using SprintPilot.Application;
using SprintPilot.Domain;
using SprintPilot.Infrastructure;
int checks=0;
void Check(bool condition,string label){if(!condition)throw new Exception("FAIL: "+label);checks++;Console.WriteLine("PASS: "+label);}
void Reject(Action action,string label){try{action();}catch(TrackerException){Check(true,label);return;}throw new Exception("Expected rejection: "+label);}
string Review(int id)=>$"=== WORK ITEM {id} ===\nTITLE:\nImprove timeout diagnostics\nDESCRIPTION:\nPreserve existing behavior.\nACCEPTANCE CRITERIA:\n- Existing scenarios pass.\nTECHNICAL NOTES:\nUse the existing handler.\nTESTING:\n- Run regression tests.\nTAGS:\nAPI; Reliability\nQUESTIONS / MISSING INFORMATION:\n- Which timeout threshold applies?\n=== END WORK ITEM {id} ===";
var parsed=AiReview.Parse(Review(1)+"\n\n"+Review(2),[1,2]);Check(parsed.Length==2&&parsed[1].Id==2,"Batch IDs map exactly");
Reject(()=>AiReview.Parse(Review(1)+"\n"+Review(1),[1]),"Duplicate IDs rejected");
Reject(()=>AiReview.Parse(Review(3),[1]),"Unknown IDs rejected");
Reject(()=>AiReview.Parse(Review(1),[1,2]),"Missing batch items rejected");
Reject(()=>AiReview.Parse(Review(1).Replace("END WORK ITEM 1","END WORK ITEM 2"),[1]),"Mismatched closing ID rejected");
Reject(()=>AiReview.Parse(Review(1).Replace("TESTING:","TEST PLAN:"),[1]),"Missing standardized section rejected");
Reject(()=>AiReview.Parse("Extra commentary\n"+Review(1),[1]),"Text outside blocks rejected");
Reject(()=>AiReview.Parse(Review(1).Replace("Improve timeout diagnostics",""),[1]),"Empty reviewed title rejected");
var changes=AiReview.Changes(parsed[0]);Check(!changes.Any(c=>c.Value?.ToString()?.Contains("Which timeout threshold")==true),"Questions are not written as invented requirements");
Check(changes.Single(c=>c.Field==ItemField.Description).Value!.ToString()!.Contains("TECHNICAL NOTES"),"Technical notes remain in proposed description");
Check(ContentText.HtmlEncode("<script>alert('x')</script>").Contains("&lt;script&gt;"),"Untrusted review HTML is encoded");
var demo=new DemoTracker();var meta=await demo.MetadataAsync();var sprint=meta.Iterations[1];var rows=await demo.SprintAsync(sprint.Path);var original=rows[0];
var first=await demo.UpdateAsync(new(original,[new(ItemField.Title,"A concurrent server title")]));
try{await demo.UpdateAsync(new(original,[new(ItemField.Title,"A stale overwrite")]));throw new Exception("Stale write accepted");}catch(TrackerException){Check((await demo.GetAsync(original.Id)).Title==first.Title,"Stale revision cannot overwrite current state");}
var bulk=new BulkEditor(demo);var results=await bulk.ApplyAsync([new(original,[new(ItemField.Title,"Stale")]),new(rows[1],[new(ItemField.Tags,"Verified")])]);Check(results.Count(r=>r.Success)==1&&results.Count(r=>!r.Success)==1,"Partial batch preserves successful and failed outcomes");
Check(!Quality.Finished(new(){Type="Product Backlog Item",State="Resolved"},meta),"Resolved is not assumed completed");
var preferences=new Preferences();foreach(var k in preferences.QualityWeights.Keys.ToArray())preferences.QualityWeights[k]=0;
Check(Quality.Evaluate(original,preferences,rows).Score==0,"Disabled quality rules do not divide by zero");
Check(Quality.Similar("Handle API timeout errors","API timeout errors handle"),"Similar titles use token overlap");
Check(!Quality.Similar("",""),"Empty titles do not cause a similarity division error");
Check(!Quality.Issues(original with{Parent=null},meta,new Preferences(),rows,sprint).Contains("Missing parent"),"Missing parents are not treated as sprint cleanup work");
var moved=ItemChanges.Apply(rows[1],[new(ItemField.Iteration,meta.Iterations[2].Path)],meta);Check(rows[1].Iteration==sprint.Path&&moved.Iteration!=sprint.Path,"Optimistic changes preserve rollback snapshot");

var example=PlanningExample.Create(new DateOnly(2026,9,15));
var planning=Planning.Build(example.Items,example.Metadata,example.Settings,example.Today,DateTimeOffset.UtcNow);
PlanningPeriod Horizon(PlanningSnapshot snap,PlanningHorizon h)=>snap.Periods.Single(p=>p.Horizon==h);
Check(Horizon(planning,PlanningHorizon.Current).KnownEstimate==226,"Current-sprint unique estimate total");
Check(Horizon(planning,PlanningHorizon.Next).KnownEstimate==176,"Next-sprint known hours exclude unknown values");
Check(Horizon(planning,PlanningHorizon.Backlog).KnownEstimate==170,"Backlog includes unscheduled and overdue open work");
Check(Horizon(planning,PlanningHorizon.Total).KnownEstimate==572,"Whole-team total includes all open horizons exactly once");
Check(Horizon(planning,PlanningHorizon.NextWeek).KnownEstimate==226,"Next week uses full estimates from overlapping sprints");
Check(planning.NextWeekStart==new DateOnly(2026,9,21),"Next week begins the following Monday");
Check(Planning.Build(example.Items,example.Metadata,example.Settings,new DateOnly(2026,9,21),DateTimeOffset.UtcNow).NextWeekStart==new DateOnly(2026,9,28),"On Monday next week still means the following Monday");
var duplicate=Planning.Build(example.Items.Concat([example.Items[0]]),example.Metadata,example.Settings,example.Today,DateTimeOffset.UtcNow);
Check(Horizon(duplicate,PlanningHorizon.Total).KnownEstimate==572,"Duplicate IDs cannot inflate totals");
var task=example.Items[0] with{Id=99990,Type="Task",Estimate=1000};
var completed=example.Items[0] with{Id=99991,State="Done",Estimate=1000};
var without=Planning.Build(example.Items.Concat([task,completed]),example.Metadata,example.Settings,example.Today,DateTimeOffset.UtcNow);
Check(Horizon(without,PlanningHorizon.Total).KnownEstimate==572,"Tasks and completed backlog items are excluded");
var apps=Planning.Distribution(Horizon(planning,PlanningHorizon.Total),example.Settings,TagDimension.Application);
var initiatives=Planning.Distribution(Horizon(planning,PlanningHorizon.Total),example.Settings,TagDimension.Initiative);
Check(Math.Abs(apps.Sum(a=>a.Effort)-572)<.00001&&Math.Abs(initiatives.Sum(a=>a.Effort)-572)<.00001,"Each split dimension independently reconciles to the unique total");
Check(apps.Single(a=>a.Unclassified).Effort==8,"Unclassified effort remains visible");
var split=Planning.Distribution(Horizon(planning,PlanningHorizon.Current),example.Settings,TagDimension.Application).Single(a=>a.Tag=="Pablo API").Effort;
example.Settings.Allocation=TagAllocation.FullMembership;
var full=Planning.Distribution(Horizon(planning,PlanningHorizon.Current),example.Settings,TagDimension.Application).Single(a=>a.Tag=="Pablo API").Effort;
Check(full==split+8,"Full membership counts the complete shared item; split uses half");
Check(planning.People.Single(p=>p.Id=="johan").Current.Status=="Above target","Over-capacity status uses sprint maximum");
Check(planning.People.Single(p=>p.Id=="kevin").Current.Status=="Within target","50–60 hours is a per-sprint target band");
Check(planning.People.Single(p=>p.Id=="piotr").Current.Status=="Room for work","Low complete estimate identifies planning headroom");
var withMissing=Planning.Build(example.Items.Append(example.Items[0] with{Id=99992,OwnerId="piotr",Estimate=null}),example.Metadata,example.Settings,example.Today,DateTimeOffset.UtcNow);
Check(withMissing.People.Single(p=>p.Id=="piotr").Current.Status=="Estimates missing","Unknown effort cannot look like available capacity");
example.Settings.EstimatesAreHours=false;
Check(Planning.Build(example.Items,example.Metadata,example.Settings,example.Today,DateTimeOffset.UtcNow).People.Single(p=>p.Id=="kevin").Current.Status=="Confirm hour units","Hour comparison is gated on explicit unit confirmation");
example.Settings.EstimatesAreHours=true;
example.Settings.CapacityOverrides[PlanningSettings.CapacityKey("kevin",planning.Current!.Id)]=new(20,30);
var custom=Planning.Build(example.Items,example.Metadata,example.Settings,example.Today,DateTimeOffset.UtcNow);
Check(custom.People.Single(p=>p.Id=="kevin").Current.Status=="Above target"&&custom.People.Single(p=>p.Id=="kevin").Next.Target.Maximum==60,"Capacity override affects only the selected person and sprint");
example.Settings.CapacityOverrides.Remove(PlanningSettings.CapacityKey("kevin",planning.Current!.Id));
example.Settings.PersonCapacityHours["kevin"]=42;
var personDefault=Planning.Build(example.Items,example.Metadata,example.Settings,example.Today,DateTimeOffset.UtcNow);
Check(personDefault.People.Single(p=>p.Id=="kevin").Current.Target.Maximum==42&&personDefault.People.Single(p=>p.Id=="kevin").Next.Target.Maximum==42,"Per-person capacity becomes the default across sprints");
var emptyTeam=example.Metadata with{People=[..example.Metadata.People,new("empty","No work","empty@example.test")]};
Check(Planning.Build(example.Items,emptyTeam,example.Settings,example.Today,DateTimeOffset.UtcNow).People.Any(p=>p.Id=="empty"&&p.Current.Count==0),"People with no assigned work remain visible");
var upper=example.Items[0] with{Tags=["pablo api","PABLO API"]};
Check(Planning.Distribution(new(PlanningHorizon.Total,"","",[upper]),example.Settings,TagDimension.Application).Single(a=>a.Tag=="Pablo API").Effort==24,"Tag matching is case-insensitive and duplicate-safe");
example.Settings.EstimateFields[upper.Type]="Custom.Hours";
Check(Planning.Estimate(upper,example.Settings)is null,"Missing custom hour field stays unknown instead of falling back to points");
Check(Planning.Estimate(upper with{NumericFields=new(){["Custom.Hours"]=7}},example.Settings)==7,"Selected custom field drives planning estimates");
Check(Planning.Estimate(upper with{NumericFields=new(){["Custom.Hours"]=-1}},example.Settings)is null,"Invalid negative effort is treated as unknown");
example.Settings.DefaultTarget=new(60,50);
Reject(()=>Planning.Validate(example.Settings),"Invalid capacity band rejected");
var empty=Planning.Build([],example.Metadata,new PlanningSettings(),example.Today,DateTimeOffset.UtcNow);
Check(empty.Periods.All(p=>p.KnownEstimate==0)&&empty.People.Length==4,"Empty backlog remains a valid zero-work dashboard");
Check(PublicHolidays.For("BE",2026).Any(h=>h.Name=="Easter Monday"&&h.Date==new DateOnly(2026,4,6)),"Built-in Belgium calendar calculates Easter Monday");
Check(PublicHolidays.For("CA",2026).Any(h=>h.Name=="Thanksgiving"&&h.Date==new DateOnly(2026,10,12)),"Built-in Canada calendar calculates Thanksgiving");
Check(PublicHolidays.For("CA-QC",2026).Any(h=>h.Name=="Québec National Holiday"&&h.Date==new DateOnly(2026,6,24)),"Built-in Quebec calendar includes the national holiday");
Check(PublicHolidays.For("CZ",2026).Any(h=>h.Name=="Czech Statehood Day"&&h.Date==new DateOnly(2026,9,28)),"Built-in Czech calendar includes statehood day");
Console.WriteLine($"{checks} unit checks passed.");
