using System.Globalization;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using SprintPilot.Application;
using SprintPilot.Domain;
using ConnectionInfo = SprintPilot.Domain.ConnectionInfo;
namespace SprintPilot.Web.Components.Pages;
public partial class Home {
 PlanningPage? planner;
 Preferences prefs=new();Metadata? meta;ConnectionInfo? connection;Person? testUser;
 string organization="",project="",token="",screen="workspace",message="",dialog="",dialogError="";
 bool focusDialog;bool initializing=true,connecting,hasError,loading,applying,moreFilters,descending,disposed;
 int sprintIndex,selectionAnchor=-1,templateIndex;
 string search="",ownerSearch="",stateFilter="",typeFilter="",tagFilter="",areaFilter="",priorityFilter="",quickView="Team",cleanupFilter="",sort="Order",workspaceMode="List";
 string commandSearch="",iterationSearch="",viewName="",bulkKind="",bulkValue="",aiText="";
 string templateName="",templateDescription="",templateAcceptance="",templateTags="",templateArea="";
 string newType="",newTitle="",newDescription="",newAcceptance="",newArea="",newTags="",newIteration="";int? newParent;
 readonly string[] AllColumns=["Order","ID","Type","Title","Owner","State","Iteration","Area","Estimate","Priority","Parent","Tags","Changed"];
 readonly string[] QuickViews=["My Work","Team","Unassigned","Carry-over","Bugs","Recently Changed"];
 readonly string[] Commands=["Next sprint","Previous sprint","Show my work","Show unassigned","Select all visible","Clear selection","Move selected to next sprint","Move selected to previous sprint","Assign selected","Add tag","Remove tag","Change state","New PBI","Refresh"];
 List<WorkItem> items=[],previousItems=[],related=[],tagHistory=[];readonly Dictionary<string,List<WorkItem>> sprintCache=new();
 readonly HashSet<string> ownerFilters=new(StringComparer.OrdinalIgnoreCase);int? draggedId;
 readonly HashSet<string> cleanupTagFilters=new(StringComparer.OrdinalIgnoreCase);
 readonly HashSet<int> selected=[],busy=[];readonly Dictionary<int,ItemUpdate> drafts=new();
 List<ItemUpdate> pending=[];List<UpdateResult> results=[];WorkItem? detail;WorkItem[] aiItems=[];ReviewSection[] reviews=[];
 CancellationTokenSource refreshToken=new();readonly CancellationTokenSource lifetime=new();DotNetObjectReference<Home>? reference;
 string PlanningProfileKey => Tracker.Demo ? "demo" : $"{connection?.Organization}|{connection?.Project}|{connection?.Team}";
 Iteration? CurrentSprint=>meta?.Iterations.ElementAtOrDefault(sprintIndex);
 string Adjacent(int delta)=>meta?.Iterations.ElementAtOrDefault(sprintIndex+delta)?.Name??"No sprint";
 string DateRange=>CurrentSprint?.Start is {} start?$"{start:MMM d} – {CurrentSprint.Finish:MMM d, yyyy}":"Dates not configured";
 IEnumerable<WorkItem> AllLoaded=>items.Concat(previousItems).Concat(related).DistinctBy(w=>w.Id);
 string[] TagSuggestions=>AllLoaded.Concat(tagHistory).SelectMany(w=>w.Tags).Distinct(StringComparer.OrdinalIgnoreCase).Order(StringComparer.OrdinalIgnoreCase).ToArray();
 List<WorkItem> SelectedItems=>AllLoaded.Where(w=>selected.Contains(w.Id)).ToList();
 IEnumerable<string> CommonStates {get {var sets=SelectedItems.Select(w=>meta!.Types.First(t=>t.Name==w.Type).States.Select(s=>s.Name).ToHashSet()).ToArray();if(sets.Length==0)return [];var common=sets[0];foreach(var set in sets.Skip(1))common.IntersectWith(set);return common.Order();}}
 string[] Issues(WorkItem w)=>Quality.Issues(w,meta!,prefs,AllLoaded,meta!.Iterations.FirstOrDefault(i=>i.Path==w.Iteration));
 Dictionary<string,int> CleanupCounts=>items.SelectMany(w=>Issues(w)).GroupBy(s=>s).ToDictionary(g=>g.Key,g=>g.Count()).Concat(new[]{new KeyValuePair<string,int>("Previous-sprint unfinished",previousItems.Count(w=>!Quality.Finished(w,meta!)))}).ToDictionary(x=>x.Key,x=>x.Value);
 IEnumerable<WorkItem> CleanupItems=>meta is null?[]:items.Where(w=>!Quality.Finished(w,meta));
 IEnumerable<(string Id,string Name,int Count)> CleanupPeople=>CleanupItems.GroupBy(w=>w.OwnerId).Select(g=>(Id:g.Key,Name:PersonName(g.Key),Count:g.Count())).OrderBy(x=>x.Name=="Unassigned").ThenBy(x=>x.Name);
 IEnumerable<(string Tag,int Count)> CleanupTags=>CleanupItems.SelectMany(w=>w.Tags).GroupBy(t=>t,StringComparer.OrdinalIgnoreCase).Select(g=>(Tag:g.Key,Count:g.Count())).OrderBy(x=>x.Tag);
 List<WorkItem> Visible {get{
  IEnumerable<WorkItem> rows=(quickView=="Carry-over"||cleanupFilter=="Previous-sprint unfinished")?previousItems.Where(w=>!Quality.Finished(w,meta!)):items;
  if(meta is null)return [];
  rows=rows.Where(w=>(search==""||w.Id.ToString().Contains(search)||w.Title.Contains(search,StringComparison.OrdinalIgnoreCase)||w.Tags.Any(t=>t.Contains(search,StringComparison.OrdinalIgnoreCase)))&&(ownerFilters.Count==0||ownerFilters.Contains(w.OwnerId))&&(stateFilter==""||w.State.Contains(stateFilter,StringComparison.OrdinalIgnoreCase))&&(typeFilter==""||w.Type.Contains(typeFilter,StringComparison.OrdinalIgnoreCase))&&(tagFilter==""||w.Tags.Any(t=>t.Contains(tagFilter,StringComparison.OrdinalIgnoreCase)))&&(cleanupTagFilters.Count==0||w.Tags.Any(t=>cleanupTagFilters.Contains(t)))&&(areaFilter==""||w.Area.Contains(areaFilter,StringComparison.OrdinalIgnoreCase))&&(priorityFilter==""||w.Priority?.ToString().Contains(priorityFilter)==true));
  rows=quickView switch{"My Work"=>rows.Where(w=>w.OwnerId==meta.Me.Id),"Unassigned"=>rows.Where(w=>w.OwnerId==""),"Bugs"=>rows.Where(w=>w.Type.Equals("Bug",StringComparison.OrdinalIgnoreCase)),"Recently Changed"=>rows.Where(w=>w.Changed>DateTimeOffset.UtcNow.AddDays(-3)),_=>rows};
  if(screen=="cleanup"&&cleanupFilter!=""&&cleanupFilter!="Previous-sprint unfinished")rows=rows.Where(w=>Issues(w).Contains(cleanupFilter));
  Func<WorkItem,IComparable?> key=sort switch{"Order"=>w=>w.Order,"ID"=>w=>w.Id,"Type"=>w=>w.Type,"Owner"=>w=>w.Owner,"State"=>w=>w.State,"Iteration"=>w=>w.Iteration,"Area"=>w=>w.Area,"Estimate"=>w=>w.Estimate,"Priority"=>w=>w.Priority,"Parent"=>w=>w.Parent,"Tags"=>w=>string.Join(";",w.Tags),"Changed"=>w=>w.Changed,_=>w=>w.Title};return (descending?rows.OrderByDescending(key):rows.OrderBy(key)).ThenBy(w=>w.Id).ToList();
 }}
 string DialogTitle=>dialog switch{"palette"=>"Commands","iterations"=>"Choose sprint","columns"=>"Visible columns","saveview"=>"Save view","bulk"=>"Edit selected items","review"=>"Review changes","ai"=>"AI review","create"=>"New work item",_=>"SprintPilot"};
 string BulkLabel=>bulkKind switch{"AddTag"=>"Tag to add","RemoveTag"=>"Tag to remove","Next" or "Previous" or "Iteration"=>"Target sprint",_=>bulkKind};
 protected override async Task OnInitializedAsync(){try{prefs=await Preferences.LoadAsync(lifetime.Token);prefs.QualityWeights.Remove("Parent");LoadTemplate();var c=await Credentials.GetAsync(lifetime.Token);if(c is not null){connection=c.Connection;organization=connection.Organization;project=connection.Project;await LoadWorkspace();}}catch(Exception e){Error(e);}finally{initializing=false;}}
 protected override async Task OnAfterRenderAsync(bool first){if(first){reference=DotNetObjectReference.Create(this);await JS.InvokeVoidAsync("sprintPilot.init",reference);await ApplyTheme();}if(focusDialog){focusDialog=false;await JS.InvokeVoidAsync("sprintPilot.dialog");}}
 async Task ApplyTheme()=>await JS.InvokeVoidAsync("sprintPilot.theme",prefs.Theme);
 void Notify(string text){message=text;hasError=false;}
 void Error(Exception e){var text=e is TrackerException?e.Message:e is OperationCanceledException?"Operation cancelled or timed out. Refresh to confirm server state.":"The operation could not be completed. Check the connection and try again.";if(dialog!="")dialogError=text;else{message=text;hasError=true;}}
 void ResetTest()=>testUser=null;
 void TokenInput(ChangeEventArgs e){token=e.Value?.ToString()??"";ResetTest();}
 async Task TestConnection(){connecting=true;try{Tracker.Demo=false;testUser=await Tracker.TestAsync(new(new(organization.Trim(),project.Trim()),token.Trim()),lifetime.Token);Notify("Connected to Azure DevOps as "+testUser.Name);}catch(Exception e){Error(e);}finally{connecting=false;}}
 async Task SaveConnection(){if(connecting)return;connecting=true;try{Tracker.Demo=false;var c=new Credentials(new(organization.Trim(),project.Trim()),token.Trim());testUser=await Tracker.TestAsync(c,lifetime.Token);await Credentials.SaveAsync(c,lifetime.Token);connection=c.Connection;token="";await JS.InvokeVoidAsync("sprintPilot.clearToken");await LoadWorkspace();Notify("Connected as "+testUser.Name);}catch(Exception e){Error(e);}finally{connecting=false;}}
 async Task ExploreDemo(){Tracker.Demo=true;connection=null;await LoadWorkspace();}
 void ExitDemo(){refreshToken.Cancel();Tracker.Demo=false;meta=null;items=[];selected.Clear();drafts.Clear();sprintCache.Clear();detail=null;screen="workspace";}
 void ChangeConnection(){ExitDemo();connection=null;testUser=null;}
 async Task ChangeTeam(ChangeEventArgs e){try{var c=await Credentials.GetAsync(lifetime.Token);if(c is null)return;connection=c.Connection with{Team=e.Value?.ToString()??""};await Credentials.SaveAsync(new(connection,c.Token),lifetime.Token);await LoadWorkspace();}catch(Exception ex){Error(ex);}}
 async Task LoadWorkspace(){loading=true;try{meta=await Tracker.MetadataAsync(true,lifetime.Token);if(connection is not null&&connection.Team=="")connection=connection with{Team=meta.Teams[0].Id};var now=DateTimeOffset.UtcNow;sprintIndex=Array.FindIndex(meta.Iterations,i=>i.Start<=now&&i.Finish?.AddDays(1)>now);if(sprintIndex<0)sprintIndex=0;screen="workspace";sprintCache.Clear();selected.Clear();drafts.Clear();previousItems=[];related=[];detail=null;await LoadSprint();try{tagHistory=(await Tracker.PlanningAsync(meta.Types.Where(t=>t.Name!="Task").Select(t=>t.Name).ToArray(),lifetime.Token)).Where(w=>w.Changed>=DateTimeOffset.UtcNow.AddMonths(-6)).ToList();}catch{tagHistory=[];}}catch(Exception e){Error(e);}finally{loading=false;}}
 async Task LoadSprint(bool refreshMetadata=false){refreshToken.Cancel();refreshToken.Dispose();refreshToken=CancellationTokenSource.CreateLinkedTokenSource(lifetime.Token);var ct=refreshToken.Token;var iteration=CurrentSprint;if(iteration is null){items=[];Notify("This team has no configured iterations. Configure them in Azure DevOps, then refresh.");return;}
  loading=true;if(sprintCache.TryGetValue(iteration.Path,out var hit))items=[..hit];else items=[];previousItems=[];related=[];await InvokeAsync(StateHasChanged);
  try{if(refreshMetadata)meta=await Tracker.MetadataAsync(true,ct);var fetched=await Tracker.SprintAsync(iteration.Path,ct);ct.ThrowIfCancellationRequested();items=fetched.ToList();sprintCache[iteration.Path]=[..items];if(quickView=="Carry-over"||screen=="cleanup")await LoadPrevious(ct);if(screen=="cleanup")await LoadRelated(ct);}catch(OperationCanceledException){if(!ct.IsCancellationRequested)Notify("Refresh timed out. Try again.");}catch(Exception e){if(!ct.IsCancellationRequested)Error(e);}finally{if(!ct.IsCancellationRequested)loading=false;}}
 async Task LoadPrevious(CancellationToken ct){var previous=meta?.Iterations.ElementAtOrDefault(sprintIndex-1);if(previous is null){previousItems=[];return;}previousItems=(await Tracker.SprintAsync(previous.Path,ct)).ToList();}
 async Task LoadRelated(CancellationToken ct){var ids=items.Where(w=>Quality.Finished(w,meta!)).SelectMany(w=>w.Children).Except(AllLoaded.Select(w=>w.Id)).ToArray();var list=new List<WorkItem>();foreach(var id in ids)list.Add(await Tracker.GetAsync(id,ct));related=list;}
 async Task Navigate(int delta){if(busy.Count>0||applying)return;var next=sprintIndex+delta;if(meta is null||next<0||next>=meta.Iterations.Length)return;sprintIndex=next;selected.Clear();selectionAnchor=-1;detail=null;cleanupFilter="";await LoadSprint();}
 async Task ChooseSprint(Iteration iteration){if(busy.Count>0||applying)return;sprintIndex=Array.IndexOf(meta!.Iterations,iteration);selected.Clear();detail=null;CloseDialog();await LoadSprint();}
 async Task Refresh(){if(screen=="planning"&&planner is not null){await planner.RefreshPlanning();return;}if(busy.Count>0||applying)return;sprintCache.Clear();await LoadSprint(true);if(detail is not null)await OpenById(detail.Id);}
 async Task SetQuickView(string view){quickView=view;cleanupFilter="";if(view=="Carry-over"){loading=true;try{await LoadPrevious(refreshToken.Token);}catch(Exception e){Error(e);}finally{loading=false;}}}
 void ClearFilters(){search=ownerSearch=stateFilter=typeFilter=tagFilter=areaFilter=priorityFilter=cleanupFilter="";ownerFilters.Clear();cleanupTagFilters.Clear();quickView="Team";}
 void ToggleOwner(string id){if(!ownerFilters.Add(id))ownerFilters.Remove(id);}
 void ToggleCleanupTag(string tag){if(!cleanupTagFilters.Add(tag))cleanupTagFilters.Remove(tag);}
 void SelectVisibleAndMoveNext(){selected.Clear();foreach(var w in Visible)selected.Add(w.Id);StartBulk("Next");}
 IEnumerable<IGrouping<string,WorkItem>> PeopleGroups()=>Visible.Where(w=>!Quality.Finished(w,meta!)).GroupBy(w=>w.OwnerId).OrderBy(g=>g.Key=="").ThenBy(g=>meta!.People.FirstOrDefault(p=>p.Id==g.Key)?.Name??"Unassigned");
 string PersonName(string id)=>meta?.People.FirstOrDefault(p=>p.Id==id)?.Name??"Unassigned";
 string[] SuggestedTags(WorkItem item){var words=item.Title.Split(' ',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Where(w=>w.Length>=4).ToHashSet(StringComparer.OrdinalIgnoreCase);return tagHistory.Where(w=>w.Id!=item.Id&&w.Tags.Length>0&&w.Title.Split(' ',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Count(words.Contains)>0).SelectMany(w=>w.Tags).Where(t=>!item.Tags.Contains(t,StringComparer.OrdinalIgnoreCase)).GroupBy(t=>t,StringComparer.OrdinalIgnoreCase).OrderByDescending(g=>g.Count()).ThenBy(g=>g.Key).Take(3).Select(g=>g.Key).ToArray();}
 Task AddSuggestedTag((WorkItem Item,string Tag) value)=>InlineEdit((value.Item,ItemField.Tags,string.Join("; ",value.Item.Tags.Append(value.Tag).Distinct(StringComparer.OrdinalIgnoreCase))));
 void DragStart(int id)=>draggedId=id;
 async Task DropOn(WorkItem target){if(draggedId is not {} sourceId||sourceId==target.Id)return;var ordered=items.OrderBy(w=>w.Order??double.MaxValue).ThenBy(w=>w.Id).ToList();var source=ordered.FirstOrDefault(w=>w.Id==sourceId);if(source is null)return;ordered.Remove(source);ordered.Insert(ordered.IndexOf(target),source);draggedId=null;for(var i=0;i<ordered.Count;i++){var desired=(i+1)*1000d;if(ordered[i].Order!=desired)await InlineEdit((ordered[i],ItemField.Order,desired.ToString(CultureInfo.InvariantCulture)));}}
 void SetScreen(string target){screen=target;detail=null;}
 async Task OpenCleanup(){screen="cleanup";ClearFilters();await LoadSprint();}
 void Sort(string column){if(sort==column)descending=!descending;else{sort=column;descending=false;}}
 void Select((int Id,bool Shift) e){var visible=Visible;var index=visible.FindIndex(w=>w.Id==e.Id);if(e.Shift&&selectionAnchor>=0){var anchor=visible.FindIndex(w=>w.Id==selectionAnchor);if(anchor>=0){for(int i=Math.Min(anchor,index);i<=Math.Max(anchor,index);i++)selected.Add(visible[i].Id);return;}}if(!selected.Add(e.Id))selected.Remove(e.Id);selectionAnchor=e.Id;}
 void ToggleAll(){var visible=Visible;if(visible.All(w=>selected.Contains(w.Id)))foreach(var w in visible)selected.Remove(w.Id);else foreach(var w in visible)selected.Add(w.Id);}
 void OpenDetail(WorkItem w)=>detail=w;
 async Task OpenById(int id){try{detail=await Tracker.GetAsync(id,lifetime.Token);}catch(Exception e){Error(e);}}
 void Replace(WorkItem w){var i=items.FindIndex(x=>x.Id==w.Id);if(i>=0)items[i]=w;var p=previousItems.FindIndex(x=>x.Id==w.Id);if(p>=0)previousItems[p]=w;if(detail?.Id==w.Id)detail=w;}
 static string Display(WorkItem w,ItemField f)=>f switch{ItemField.Title=>w.Title,ItemField.Owner=>w.Owner,ItemField.State=>w.State,ItemField.Iteration=>w.Iteration,ItemField.Area=>w.Area,ItemField.Estimate=>w.Estimate?.ToString(CultureInfo.InvariantCulture)??"",ItemField.Order=>w.Order?.ToString(CultureInfo.InvariantCulture)??"",ItemField.Priority=>w.Priority?.ToString()??"",ItemField.Tags=>string.Join("; ",w.Tags),ItemField.Description=>ContentText.Plain(w.Description),ItemField.Acceptance=>ContentText.Plain(w.Acceptance),_=>""};
 async Task InlineEdit((WorkItem Item,ItemField Field,string Value) edit){var w=edit.Item;if(!busy.Add(w.Id))return;try{
  if(drafts.ContainsKey(w.Id))throw new TrackerException("Apply or discard the local AI draft before editing this item.");
  object? value=edit.Value;if(edit.Field is ItemField.Estimate or ItemField.Order){if(edit.Value=="")value=null;else if(double.TryParse(edit.Value,NumberStyles.Float,CultureInfo.InvariantCulture,out var n)&&double.IsFinite(n)&&n>=0)value=n;else throw new TrackerException(edit.Field==ItemField.Order?"Order must be a non-negative number.":"Estimate must be a non-negative number.");}
  if(edit.Field==ItemField.Priority){if(int.TryParse(edit.Value,out var n)&&n>=1&&n<=4)value=n;else throw new TrackerException("Priority must be 1–4.");}
  var changes=new[]{new Change(edit.Field,value)};Replace(ItemChanges.Apply(w,changes,meta!));await InvokeAsync(StateHasChanged);var saved=await Tracker.UpdateAsync(new(w,changes),lifetime.Token);Replace(saved);sprintCache.Clear();
  if(saved.Iteration!=CurrentSprint?.Path)items.RemoveAll(x=>x.Id==saved.Id);if(saved.Iteration!=meta?.Iterations.ElementAtOrDefault(sprintIndex-1)?.Path)previousItems.RemoveAll(x=>x.Id==saved.Id);Notify($"#{w.Id} saved.");
 }catch(Exception e){Replace(w);Error(e);}finally{busy.Remove(w.Id);}}
 Task Show(string value){dialog=value;dialogError="";commandSearch="";focusDialog=true;return Task.CompletedTask;}
 void CloseDialog(){if(applying)return;dialog="";dialogError="";_=JS.InvokeVoidAsync("sprintPilot.restoreFocus");}
 void StartBulk(string kind){if(selected.Count==0){Notify("Select work items first.");return;}bulkKind=kind;bulkValue=kind switch{"Next"=>meta?.Iterations.ElementAtOrDefault(sprintIndex+1)?.Path??"","Previous"=>meta?.Iterations.ElementAtOrDefault(sprintIndex-1)?.Path??"",_=>""};_=Show("bulk");}
 void PreviewBulk(){try{if(bulkKind=="State"&&!CommonStates.Contains(bulkValue))throw new TrackerException("Choose a state supported by all selected work-item types.");if(SelectedItems.Count!=selected.Count)throw new TrackerException("Some selected items are no longer loaded. Clear selection and select again.");if(SelectedItems.Any(w=>busy.Contains(w.Id)||drafts.ContainsKey(w.Id)))throw new TrackerException("Wait for saves and apply or discard local drafts before bulk editing.");
  if(bulkValue==""&&bulkKind!="Owner")throw new TrackerException("Choose a value first.");if(bulkKind=="Priority"&&(!int.TryParse(bulkValue,out var p)||p<1||p>4))throw new TrackerException("Priority must be 1–4.");
  pending=SelectedItems.Select(w=>{Change c;if(bulkKind is "AddTag" or "RemoveTag"){var tags=w.Tags.ToList();if(bulkKind=="AddTag")tags.Add(bulkValue.Trim());else tags.RemoveAll(t=>t.Equals(bulkValue.Trim(),StringComparison.OrdinalIgnoreCase));c=new(ItemField.Tags,string.Join("; ",tags.Distinct(StringComparer.OrdinalIgnoreCase)));}else{var f=bulkKind is "Next" or "Previous"?ItemField.Iteration:Enum.Parse<ItemField>(bulkKind);c=new(f,bulkKind=="Priority"?int.Parse(bulkValue):bulkValue);}return new ItemUpdate(w,[c]);}).ToList();results=[];dialog="review";dialogError="";
 }catch(Exception e){Error(e);}}
 async Task ApplyPending(){if(applying)return;applying=true;dialogError="";results=[];foreach(var p in pending)busy.Add(p.Original.Id);try{
  var progress=new Progress<UpdateResult>(r=>{if(disposed)return;_=InvokeAsync(()=>{results.RemoveAll(x=>x.Id==r.Id);results.Add(r);if(r.Item is not null){Replace(r.Item);drafts.Remove(r.Id);}StateHasChanged();});});
  results=(await Bulk.ApplyAsync(pending,progress,lifetime.Token)).ToList();foreach(var r in results.Where(r=>r.Success)){Replace(r.Item!);drafts.Remove(r.Id);}sprintCache.Clear();items.RemoveAll(w=>w.Iteration!=CurrentSprint?.Path);previousItems.RemoveAll(w=>w.Iteration!=meta?.Iterations.ElementAtOrDefault(sprintIndex-1)?.Path);Notify($"{results.Count(r=>r.Success)} updated; {results.Count(r=>!r.Success)} failed.");
 }catch(Exception e){Error(e);}finally{foreach(var p in pending)busy.Remove(p.Original.Id);applying=false;}}
 async Task RetryFailed(){applying=true;try{var failed=results.Where(r=>!r.Success).Select(r=>r.Id).ToHashSet();var next=new List<ItemUpdate>();foreach(var p in pending.Where(p=>failed.Contains(p.Original.Id))){var fresh=await Tracker.GetAsync(p.Original.Id,lifetime.Token);Replace(fresh);next.Add(new(fresh,p.Changes));}pending=next;results=[];dialogError="Review the refreshed current values before applying the retry.";}catch(Exception e){Error(e);}finally{applying=false;}}
 void PrepareNext(){if(loading||busy.Count>0){Notify("Wait for the current refresh or save to finish.");return;}if(meta?.Iterations.ElementAtOrDefault(sprintIndex+1)is null){Notify("Configure the next team sprint in Azure DevOps first.");return;}var visible=Visible.Where(w=>!Quality.Finished(w,meta)).ToArray();selected.Clear();foreach(var w in visible)selected.Add(w.Id);Notify($"{selected.Count} visible unfinished items selected. Adjust checkboxes, then use Sprint → to review the move.");}
 async Task CopySelected()=>await CopyItems(SelectedItems);
 async Task CopyItems(IEnumerable<WorkItem> source){try{var rows=source.ToArray();if(rows.Length==0)throw new TrackerException("Select work items first.");await JS.InvokeVoidAsync("sprintPilot.copy",AiReview.Export(rows,prefs.AiPrompt));Notify($"Copied {rows.Length} item(s) for AI review.");}catch(Exception e){Error(e);}}
 void PasteSelected()=>PasteItems(SelectedItems);
 void PasteItems(IEnumerable<WorkItem> source){aiItems=source.ToArray();if(aiItems.Length==0){Notify("Select work items first.");return;}aiText="";reviews=[];_=Show("ai");}
 void ParseAi(){try{reviews=AiReview.Parse(aiText,aiItems.Select(w=>w.Id).ToArray());dialogError="";}catch(Exception e){Error(e);}}
 IReadOnlyList<Change> ReviewChanges(ReviewSection review){var changes=AiReview.Changes(review).ToList();var original=aiItems.Single(w=>w.Id==review.Id);if(!meta!.Types.First(t=>t.Name==original.Type).Fields.Contains("Microsoft.VSTS.Common.AcceptanceCriteria")){var acceptance=changes.Single(c=>c.Field==ItemField.Acceptance);changes.Remove(acceptance);var desc=changes.Single(c=>c.Field==ItemField.Description);changes.Remove(desc);changes.Add(new(ItemField.Description,desc.Value+ContentText.HtmlEncode("\n\nACCEPTANCE CRITERIA:\n"+review.Sections["ACCEPTANCE CRITERIA"])));}return changes;}
 void ApplyAiLocally(){foreach(var r in reviews)drafts[r.Id]=new(aiItems.Single(w=>w.Id==r.Id),ReviewChanges(r));CloseDialog();Notify($"{reviews.Length} local draft(s) prepared. Open an item to review and save. Drafts are lost when the session ends.");}
 void ReviewAiServer(){pending=reviews.Select(r=>new ItemUpdate(aiItems.Single(w=>w.Id==r.Id),ReviewChanges(r))).ToList();results=[];dialog="review";dialogError="";}
 void ReviewDraft(int id){pending=[drafts[id]];results=[];_=Show("review");}
 void NewItem(){if(meta is null){Notify("Connect to Azure DevOps or open demo mode first.");return;}newType=meta.Types.FirstOrDefault(t=>t.Name is "Product Backlog Item" or "User Story")?.Name??meta.Types.First().Name;newTitle=newDescription=newAcceptance=newTags="";newArea=meta.Scope.FirstOrDefault()?.Path??meta.Areas.FirstOrDefault()??"";newIteration=CurrentSprint?.Path??"";newParent=null;_=Show("create");}
 void ApplyCreateTemplate(ChangeEventArgs e){if(int.TryParse(e.Value?.ToString(),out var index)&&prefs.Templates.ElementAtOrDefault(index)is {} t){newDescription=t.Description;newAcceptance=t.Acceptance;newTags=t.Tags;if(t.Area!="")newArea=t.Area;}}
 async Task CreateItem(){if(applying)return;applying=true;try{if(string.IsNullOrWhiteSpace(newTitle)||newTitle.Length>255)throw new TrackerException("Enter a title between 1 and 255 characters.");var changes=new List<Change>{new(ItemField.Title,newTitle.Trim()),new(ItemField.Description,ContentText.HtmlEncode(newDescription)),new(ItemField.Area,newArea),new(ItemField.Iteration,newIteration),new(ItemField.Tags,newTags)};
  if(newAcceptance!=""){if(meta!.Types.First(t=>t.Name==newType).Fields.Contains("Microsoft.VSTS.Common.AcceptanceCriteria"))changes.Add(new(ItemField.Acceptance,ContentText.HtmlEncode(newAcceptance)));else{changes.RemoveAll(c=>c.Field==ItemField.Description);changes.Add(new(ItemField.Description,ContentText.HtmlEncode(newDescription+"\n\nACCEPTANCE CRITERIA:\n"+newAcceptance)));}}var w=await Tracker.CreateAsync(newType,changes,newParent,lifetime.Token);if(w.Iteration==CurrentSprint?.Path)items.Add(w);sprintCache.Clear();detail=w;dialog="";Notify($"Created #{w.Id}.");
 }catch(Exception e){Error(e);}finally{applying=false;}}
 async Task ToggleColumn(string c){prefs.Columns=prefs.Columns.Contains(c)?prefs.Columns.Where(x=>x!=c).ToArray():AllColumns.Where(x=>prefs.Columns.Contains(x)||x==c).ToArray();await SaveSettings();}
 Dictionary<string,string> Filters()=>new(){["search"]=search,["owners"]=string.Join('|',ownerFilters),["state"]=stateFilter,["type"]=typeFilter,["tag"]=tagFilter,["area"]=areaFilter,["priority"]=priorityFilter,["quick"]=quickView,["sort"]=sort,["descending"]=descending.ToString()};
 async Task SaveView(){if(string.IsNullOrWhiteSpace(viewName)){dialogError="Enter a view name.";return;}prefs.Views.RemoveAll(v=>v.Name.Equals(viewName.Trim(),StringComparison.OrdinalIgnoreCase));prefs.Views.Add(new(viewName.Trim(),Filters(),prefs.Columns.ToArray()));await SaveSettings();CloseDialog();viewName="";}
 async Task LoadView(SavedView v){var f=v.Filters;search=f.GetValueOrDefault("search","");ownerFilters.Clear();foreach(var id in f.GetValueOrDefault("owners",f.GetValueOrDefault("owner","")).Split('|',StringSplitOptions.RemoveEmptyEntries))ownerFilters.Add(id);stateFilter=f.GetValueOrDefault("state","");typeFilter=f.GetValueOrDefault("type","");tagFilter=f.GetValueOrDefault("tag","");areaFilter=f.GetValueOrDefault("area","");priorityFilter=f.GetValueOrDefault("priority","");sort=f.GetValueOrDefault("sort","Order");descending=f.GetValueOrDefault("descending")=="True";prefs.Columns=v.Columns;screen="workspace";await SetQuickView(f.GetValueOrDefault("quick","Team"));}
 async Task DeleteView(SavedView v){prefs.Views.Remove(v);await SaveSettings();}
 async Task SaveSettings(){try{await Preferences.SaveAsync(prefs,lifetime.Token);await ApplyTheme();Notify("Settings saved.");}catch(Exception e){Error(e);}}
 void LoadTemplate(){if(prefs.Templates.ElementAtOrDefault(templateIndex)is not {} t)return;templateName=t.Name;templateDescription=t.Description;templateAcceptance=t.Acceptance;templateTags=t.Tags;templateArea=t.Area;}
 void NewTemplate(){prefs.Templates.Add(new("New template","","","",""));templateIndex=prefs.Templates.Count-1;LoadTemplate();}
 async Task DeleteTemplate(){if(templateIndex>=0&&templateIndex<prefs.Templates.Count)prefs.Templates.RemoveAt(templateIndex);templateIndex=0;LoadTemplate();await SaveSettings();}
 async Task SaveTemplate(){if(templateName.Trim()==""){Notify("Enter a template name.");return;}var t=new WorkTemplate(templateName.Trim(),templateDescription,templateAcceptance,templateTags,templateArea);if(templateIndex<prefs.Templates.Count)prefs.Templates[templateIndex]=t;else prefs.Templates.Add(t);await SaveSettings();}
 static bool SafeLink(string url)=>Uri.TryCreate(url,UriKind.Absolute,out var uri)&&uri.Scheme=="https"&&(uri.Host=="dev.azure.com"||uri.Host.EndsWith(".visualstudio.com",StringComparison.OrdinalIgnoreCase));
 async Task RunCommand(string command){CloseDialog();switch(command){case "Next sprint":await Navigate(1);break;case "Previous sprint":await Navigate(-1);break;case "Show my work":await SetQuickView("My Work");break;case "Show unassigned":await SetQuickView("Unassigned");break;case "Select all visible":foreach(var w in Visible)selected.Add(w.Id);break;case "Clear selection":selected.Clear();break;case "Move selected to next sprint":StartBulk("Next");break;case "Move selected to previous sprint":StartBulk("Previous");break;case "Assign selected":StartBulk("Owner");break;case "Add tag":StartBulk("AddTag");break;case "Remove tag":StartBulk("RemoveTag");break;case "Change state":StartBulk("State");break;case "New PBI":NewItem();break;case "Refresh":await Refresh();break;}}
 [JSInvokable]public async Task Shortcut(string command){if(applying)return;if(command=="escape"){if(dialog!="")CloseDialog();else detail=null;}else if(dialog==""){switch(command){case "palette":await Show("palette");break;case "search":await JS.InvokeVoidAsync("sprintPilot.focusSearch");break;case "next":await Navigate(1);break;case "previous":await Navigate(-1);break;case "refresh":if(meta is not null)await Refresh();break;case "select":foreach(var w in Visible)selected.Add(w.Id);break;}}await InvokeAsync(StateHasChanged);}
 public async ValueTask DisposeAsync(){disposed=true;lifetime.Cancel();refreshToken.Cancel();try{await JS.InvokeVoidAsync("sprintPilot.dispose");}catch(JSDisconnectedException){}reference?.Dispose();refreshToken.Dispose();lifetime.Dispose();}
}
