using SprintPilot.Application;
using SprintPilot.Domain;
namespace SprintPilot.Infrastructure;
public sealed class DemoTracker:IWorkTracker {
 readonly Dictionary<int,WorkItem> items=new();readonly Dictionary<int,List<WorkItemComment>> comments=new();readonly Metadata metadata;readonly object sync=new();readonly List<GitBranch> demoBranches=[];readonly List<GitPullRequest> demoPullRequests=[];
 public DemoTracker(){var today=DateTimeOffset.UtcNow.Date;var monday=today.AddDays(-((int)today.DayOfWeek+6)%7);var iterations=Enumerable.Range(-1,3).Select(i=>new Iteration((i+2).ToString(),$"Sprint {18+i}",$"SprintPilot\\Sprint {18+i}",monday.AddDays(i*14),monday.AddDays(i*14+13))).ToArray();
  Person[] people=[new("kevin","Kevin","kevin@example.test"),new("johan","Johan","johan@example.test"),new("piotr","Piotr","piotr@example.test"),new("bea","Bea","bea@example.test")];
  string[] fields=["System.Title","System.AssignedTo","System.State","System.IterationPath","System.AreaPath","Microsoft.VSTS.Scheduling.StoryPoints","Microsoft.VSTS.Common.Priority","System.Tags","System.Description","Microsoft.VSTS.Common.AcceptanceCriteria"];
  metadata=new([new("demo","Platform team")],people,iterations,["SprintPilot\\Platform","SprintPilot\\Experience"],[..new[]{"Product Backlog Item","Bug","Task"}.Select(n=>new TypeDefinition(n,[new("New","Proposed"),new("Active","InProgress"),new("Resolved","Resolved"),new("Closed","Completed")],fields,"Microsoft.VSTS.Scheduling.StoryPoints"))],[new("SprintPilot",true)],people[0]);
  string[] titles=["Pablo API timeout handling","CNX migration validation","Automate DR deployment pipeline","FrontCare account recovery","Review database failover alerts","Improve claim search latency","Document rollback procedure","Add migration failure notification","Handle duplicate queue messages","Review API contract changes","Verify session expiry behavior","Clean up obsolete feature flags"];
  for(int i=0;i<titles.Length;i++){var owner=people[i%4];items[5210+i]=new(){Id=5210+i,Revision=1,Title=titles[i],Type=i%4==0?"Bug":"Product Backlog Item",Owner=i%5==0?"":owner.Name,OwnerId=i%5==0?"":owner.Id,State=i%4==0?"New":i%4==3?"Closed":"Active",Iteration=iterations[i<9?1:0].Path,Area=metadata.Areas[i%2],Estimate=i%3==0?null:i%5+1,Priority=i%3+1,Parent=i%4==0?null:5000,Tags=i%3==0?[]:[i%2==0?"API":"DR","Platform"],Changed=DateTimeOffset.UtcNow.AddDays(-i*2),Description="<p>Improve the reliability of this workflow. Preserve existing behavior and document the operational impact.</p>",Acceptance="<p>Given a valid request, when the workflow completes, then the expected result is available.</p><p>Testing: cover success and failure paths.</p>"};}
  foreach(var item in PlanningExample.Create(DateOnly.FromDateTime(DateTime.Now)).Items)items[item.Id]=item;
  demoBranches.AddRange([
   new("main","1111111111111111111111111111111111111111","Kevin","Kevin",DateTimeOffset.UtcNow.AddDays(-1),"Merge current sprint changes",true,true,false,true),
   new("feature/frontcare-recovery","2222222222222222222222222222222222222222","Bea","Bea",DateTimeOffset.UtcNow.AddDays(-12),"Add recovery validation",false,false,true,false),
   new("feature/old-claim-search","3333333333333333333333333333333333333333","Johan","Johan",DateTimeOffset.UtcNow.AddDays(-126),"Finish claim search optimization",false,false,false,true),
   new("bugfix/legacy-timeout","4444444444444444444444444444444444444444","Piotr","Piotr",DateTimeOffset.UtcNow.AddDays(-224),"Handle legacy timeout response",false,false,false,false),
   new("release/2025-q4","5555555555555555555555555555555555555555","Kevin","Kevin",DateTimeOffset.UtcNow.AddDays(-270),"Prepare Q4 release",false,false,false,true),
   new("experiment/queue-prototype","6666666666666666666666666666666666666666","Johan","Johan",DateTimeOffset.UtcNow.AddDays(-38),"Prototype queue routing",false,false,false,false)
  ]);
  demoPullRequests.AddRange([
   new(41,"FrontCare recovery validation","feature/frontcare-recovery","main","Bea",DateTimeOffset.UtcNow.AddDays(-10),false,"2222222222222222222222222222222222222222","Bea",DateTimeOffset.UtcNow.AddDays(-2),"Address review feedback",2,1,0,"succeeded","https://dev.azure.com/demo/SprintPilot/_git/SprintPilot/pullrequest/41"),
   new(42,"Old claim search experiment","feature/old-claim-search","main","Johan",DateTimeOffset.UtcNow.AddDays(-145),true,"3333333333333333333333333333333333333333","Johan",DateTimeOffset.UtcNow.AddDays(-126),"Finish claim search optimization",1,0,0,"notSet","https://dev.azure.com/demo/SprintPilot/_git/SprintPilot/pullrequest/42"),
   new(43,"Legacy timeout cleanup","bugfix/legacy-timeout","main","Piotr",DateTimeOffset.UtcNow.AddDays(-260),false,"4444444444444444444444444444444444444444","Piotr",DateTimeOffset.UtcNow.AddDays(-224),"Handle legacy timeout response",2,0,0,"conflicts","https://dev.azure.com/demo/SprintPilot/_git/SprintPilot/pullrequest/43"),
   new(44,"Release 2025 Q4","release/2025-q4","main","Kevin",DateTimeOffset.UtcNow.AddDays(-280),false,"5555555555555555555555555555555555555555","Kevin",DateTimeOffset.UtcNow.AddDays(-270),"Prepare Q4 release",3,0,0,"notSet","https://dev.azure.com/demo/SprintPilot/_git/SprintPilot/pullrequest/44"),
   new(45,"Queue routing prototype","experiment/queue-prototype","main","Johan",DateTimeOffset.UtcNow.AddDays(-40),true,"6666666666666666666666666666666666666666","Johan",DateTimeOffset.UtcNow.AddDays(-38),"Prototype queue routing",0,0,0,"notSet","https://dev.azure.com/demo/SprintPilot/_git/SprintPilot/pullrequest/45"),
   new(46,"Waiting on architecture decision","feature/architecture-decision","main","Kevin",DateTimeOffset.UtcNow.AddDays(-190),false,"8888888888888888888888888888888888888888","Kevin",DateTimeOffset.UtcNow.AddDays(-181),"Update architecture options",2,0,1,"notSet","https://dev.azure.com/demo/SprintPilot/_git/SprintPilot/pullrequest/46")
  ]);
 }
 public Task<Person> TestAsync(Credentials c,CancellationToken ct=default)=>Task.FromResult(metadata.Me);
 public Task<Metadata> MetadataAsync(bool refresh=false,CancellationToken ct=default)=>Task.FromResult(metadata);
 public Task<IReadOnlyList<WorkItem>> SprintAsync(string iteration,CancellationToken ct=default){lock(sync){var rows=items.Values.Where(i=>i.Iteration==iteration).OrderBy(i=>i.Order??double.MaxValue).ThenBy(i=>i.Id).Select((w,i)=>w with{Order=i+1}).ToArray();return Task.FromResult<IReadOnlyList<WorkItem>>(rows);}}
 public Task ReorderSprintAsync(string iterationId,string iterationPath,int id,int previousId,int nextId,CancellationToken ct=default){lock(sync){var rows=items.Values.Where(i=>i.Iteration==iterationPath).OrderBy(i=>i.Order??double.MaxValue).ThenBy(i=>i.Id).ToList();var item=rows.FirstOrDefault(i=>i.Id==id)??throw new TrackerException("Demo sprint item not found.");rows.Remove(item);var index=previousId==0?0:rows.FindIndex(i=>i.Id==previousId)+1;if(nextId!=0){var next=rows.FindIndex(i=>i.Id==nextId);if(next>=0)index=next;}index=Math.Clamp(index,0,rows.Count);rows.Insert(index,item);for(var i=0;i<rows.Count;i++)items[rows[i].Id]=rows[i] with{Order=i+1};return Task.CompletedTask;}}
 public Task<SprintCapacity> CapacityAsync(string iterationId,CancellationToken ct=default){var sprint=metadata.Iterations.FirstOrDefault(i=>i.Id==iterationId);if(sprint?.Start is not {} start)return Task.FromResult(new SprintCapacity([],[]));var members=metadata.People.Select((p,i)=>new MemberCapacity(p.Id,p.Name,i==1?[new DateRange(start.AddDays(3),start.AddDays(3))]:[],6)).ToArray();return Task.FromResult(new SprintCapacity(members,[]));}
 public Task<IReadOnlyList<AzureProject>> ProjectsAsync(CancellationToken ct=default)=>Task.FromResult<IReadOnlyList<AzureProject>>([new("demo","SprintPilot"),new("archive","Archive tools")]);
 public Task<IReadOnlyList<GitRepository>> RepositoriesAsync(string project,CancellationToken ct=default)=>Task.FromResult<IReadOnlyList<GitRepository>>(project=="Archive tools"?[new("archive-repo","Migration archive","main")]:[new("demo-repo","SprintPilot","main"),new("demo-api","Pablo API","main")]);
 public Task<IReadOnlyList<GitBranch>> BranchesAsync(string project,string repositoryId,CancellationToken ct=default){lock(sync)return Task.FromResult<IReadOnlyList<GitBranch>>(repositoryId=="demo-repo"?demoBranches.ToArray():[new("main","7777777777777777777777777777777777777777","Kevin","Kevin",DateTimeOffset.UtcNow.AddDays(-3),"Repository baseline",true,true,false,true)]);}
 public Task<IReadOnlyList<BranchDeleteResult>> DeleteBranchesAsync(string project,string repositoryId,IReadOnlyList<BranchDeleteRequest> branches,CancellationToken ct=default){lock(sync){var result=new List<BranchDeleteResult>();foreach(var request in branches){var found=demoBranches.FirstOrDefault(b=>b.Name.Equals(request.Name,StringComparison.OrdinalIgnoreCase)&&b.ObjectId.Equals(request.ObjectId,StringComparison.OrdinalIgnoreCase));if(found is null){result.Add(new(request.Name,false,"Branch changed or no longer exists. Refresh and review it again."));continue;}if(found.IsDefault||found.IsLocked){result.Add(new(request.Name,false,"Default or locked branches cannot be deleted."));continue;}demoBranches.Remove(found);result.Add(new(request.Name,true,null));}return Task.FromResult<IReadOnlyList<BranchDeleteResult>>(result);}}
 public Task<IReadOnlyList<GitPullRequest>> PullRequestsAsync(string project,string repositoryId,CancellationToken ct=default){lock(sync)return Task.FromResult<IReadOnlyList<GitPullRequest>>(repositoryId=="demo-repo"?demoPullRequests.ToArray():[]);}
 public Task<IReadOnlyList<GitPullRequestSignal>> PullRequestSignalsAsync(string project,string repositoryId,CancellationToken ct=default){lock(sync)return Task.FromResult<IReadOnlyList<GitPullRequestSignal>>(repositoryId=="demo-repo"?demoPullRequests.Select(p=>new GitPullRequestSignal(p.Id,p.Title,p.SourceBranch,"active",p.CreatedDate)).ToArray():[]);}
 public Task<IReadOnlyList<PullRequestAbandonResult>> AbandonPullRequestsAsync(string project,string repositoryId,IReadOnlyList<PullRequestAbandonRequest> pullRequests,CancellationToken ct=default){lock(sync){var result=new List<PullRequestAbandonResult>();foreach(var request in pullRequests){var found=demoPullRequests.FirstOrDefault(p=>p.Id==request.Id);if(found is null){result.Add(new(request.Id,false,"Pull request is no longer active. Refresh before retrying."));continue;}if(!found.SourceCommitId.Equals(request.SourceCommitId,StringComparison.OrdinalIgnoreCase)){result.Add(new(request.Id,false,"The source branch changed after review. Refresh and review the pull request again."));continue;}demoPullRequests.Remove(found);result.Add(new(request.Id,true,null));}return Task.FromResult<IReadOnlyList<PullRequestAbandonResult>>(result);}}
 public Task<IReadOnlyList<WorkItem>> PlanningAsync(string[] types,CancellationToken ct=default){lock(sync)return Task.FromResult<IReadOnlyList<WorkItem>>(items.Values.Where(w=>types.Contains(w.Type)).ToArray());}
 public Task<WorkItem> GetAsync(int id,CancellationToken ct=default){lock(sync)return Task.FromResult(items.GetValueOrDefault(id)??throw new TrackerException("Demo item not found."));}
 public Task<IReadOnlyList<WorkItemComment>> CommentsAsync(int id,CancellationToken ct=default){lock(sync)return Task.FromResult<IReadOnlyList<WorkItemComment>>(comments.GetValueOrDefault(id)??[]);}
 public Task<WorkItemComment> AddCommentAsync(int id,string text,CancellationToken ct=default){lock(sync){if(!items.ContainsKey(id))throw new TrackerException("Demo item not found.");if(string.IsNullOrWhiteSpace(text))throw new TrackerException("Enter a comment first.");var list=comments.GetValueOrDefault(id);if(list is null){list=[];comments[id]=list;}var comment=new WorkItemComment(list.Count+1,text.Trim(),metadata.Me.Name,DateTimeOffset.UtcNow);list.Add(comment);items[id]=items[id] with{CommentCount=list.Count,Changed=DateTimeOffset.UtcNow};return Task.FromResult(comment);}}
 public Task<WorkItem> UpdateAsync(ItemUpdate u,CancellationToken ct=default){lock(sync){if(items[u.Original.Id].Revision!=u.Original.Revision)throw new TrackerException("Revision conflict. Refresh before retrying.");var item=ItemChanges.Apply(u.Original,u.Changes,metadata) with{Revision=u.Original.Revision+1,Changed=DateTimeOffset.UtcNow};items[item.Id]=item;return Task.FromResult(item);}}
 public Task<WorkItem> CreateAsync(string type,IReadOnlyList<Change> changes,int? parent,CancellationToken ct=default){lock(sync){var item=ItemChanges.Apply(new(){Id=items.Keys.Max()+1,Revision=1,Type=type,State="New",Parent=parent,Changed=DateTimeOffset.UtcNow},changes,metadata);items[item.Id]=item;return Task.FromResult(item);}}

 public Task<IReadOnlyList<string>> PipelineYamlFilesAsync(string project,string repositoryId,string branch,CancellationToken ct=default)=>Task.FromResult<IReadOnlyList<string>>(new[]{"/azure-pipelines.yml","/pipelines/deploy.yml","/pipelines/infrastructure.yml"});
 public Task<IReadOnlyList<PipelineDefinition>> PipelinesAsync(string project,CancellationToken ct=default)=>Task.FromResult<IReadOnlyList<PipelineDefinition>>(Array.Empty<PipelineDefinition>());
 public Task<IReadOnlyList<PipelineCreateResult>> CreatePipelinesAsync(string project,string repositoryId,string branch,IReadOnlyList<PipelineCreateRequest> pipelines,CancellationToken ct=default)=>Task.FromResult<IReadOnlyList<PipelineCreateResult>>(pipelines.Select((p,i)=>new PipelineCreateResult(p.Name,true,1000+i,null)).ToArray());
}
